[package]
name = "tap_interceptor"
version = "0.1.0"
edition = "2021"

[dependencies]
uinput = "0.1.3"
btleplug = "0.11.6"
uuid = "1.10.0"
tokio = { version = "1.42.0", features = ["full"] }
futures-util = "0.3.31"